nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin: ['http://localhost:8001', 'http://localhost:8002', 'http://localhost:8003']
        allow_methods: ['GET', 'POST']
        allow_headers: ['Content-Type', 'Authorization', 'Accept']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['http://localhost:8001', 'http://localhost:8002', 'http://localhost:8003']
            allow_headers: ['Content-Type', 'Authorization', 'Accept']
            allow_methods: ['GET', 'POST']
