
services:
  mercure:
    image: dunglas/mercure
    container_name: mercure
    environment:
      SERVER_NAME: ":80"
      DISABLE_HTTPS: "1"

      MERCURE_PUBLISHER_JWT_KEY: 'w4vK6-qT9Y8mL3FjP2xQzR1b9W0h6uXyA-Nf7Dk5Hs0='
      MERCURE_SUBSCRIBER_JWT_KEY: 'w4vK6-qT9Y8mL3FjP2xQzR1b9W0h6uXyA-Nf7Dk5Hs0='
      MERCURE_JWT_SECRET: 'w4vK6-qT9Y8mL3FjP2xQzR1b9W0h6uXyA-Nf7Dk5Hs0='
      
      MERCURE_PUBLIC_URL: "http://localhost:3000/.well-known/mercure"
      MERCURE_URL: "http://localhost:3000/.well-known/mercure"

      MERCURE_CORS_ALLOWED_ORIGINS: http://localhost:8001, http://localhost:8002, http://localhost:8003 #, ...
      MERCURE_PUBLISH_ALLOWED_ORIGINS: http://localhost:8001, http://localhost:8002, http://localhost:8003 

      MERCURE_ALLOW_ANONYMOUS: '1'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://localhost:8001
        publish_origins http://localhost:8001
        anonymous
      
    ports:
      - "3000:80"
