parameters:

services:
    _defaults:
        autowire: true 
        autoconfigure: true
        bind:
            $open_api_key: '%env(OPENAPI_KEY)%'
            $jwt_secret_api_key: '%env(JWT_SECRET_API_KEY)%'

    App\Service\FatalErrorHandler:
        arguments:
            $bus: '@messenger.bus.default'
        lazy: false
    App\MessageHandler\ErrorReportHandler:
        tags: ['messenger.message_handler']

    App\:
        resource: '../src/'
